### ISSUE TITLE
How to add support to armv8m?

### ISSUE THREAD

**Issue by akiannillo** [capstone-engine/capstone#1724]
I'd like to add armv8m (main line) instruction set and use capstone.
How can I do that?

**Comment by XVilka** [comment]
See https://github.com/aquynh/capstone/issues/1319
Basically, you need to synchronize with the latest LLVM code (TableGen definitions).

**Comment by akiannillo** [comment]
I'm not an expert on LLVM. 
Can you guide me on where the TableGen definitions are in both projects?

**Comment by janek202** [comment]
Hi,

Were you able to move forward with this?
I'm interested in this architecture as well.

**Comment by akiannillo** [comment]
No, I was not.
Unfortunately, I have no time to acquire the knowledge to do it by myself.
Any idea from your side?

**Comment by janek202** [comment]
No, unfortunately, this is all new to me.
Currently, I don't have enough time to do it by myself.

**Comment by MostBaffled** [comment]
Capstone v4.0.2 doesn't decode vldr (amongst others) correctly. It just results in ldc instructions (which are related). Is this likely to fixed by syncing to the latest LLVM TableGen definitions as suggested above?

Latest (well, pretty recent) llvm-objdump does correctly disassemble the instructions in question.

**Comment by Rot127** [comment]
Will be done with https://github.com/capstone-engine/capstone/pull/1949
