### ISSUE TITLE
New organization for Capstone

### ISSUE THREAD

**Issue by aquynh** [capstone-engine/capstone#1787]
We moved the original historical repo of Capstone from https://github.com/aquynh/capstone to an organization, where we can add more maintainers to the project, and push Capstone development forward.

Our new home is https://github.com/capstone-engine/capstone

The imminent plan is to review & merge all the outstanding pull requests, and release version 5.0 based on the next branch soon.

Future development includes more often release and keep updating faster.

If you are willing to spend time to help the project, please contact us.

**Comment by tmfink** [comment]
I'd be happy to help, in particular with "organization-level" items like the branching strategy in #1781.
I maintain the [Rust language bindings](https://github.com/capstone-rust/capstone-rs).

**Comment by icchy** [comment]
why it's not transferred but copied? it would be helpful if issues and PRs remain as it was.
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by aquynh** [comment]
Transfering repo is a good idea, i will try that!

**Comment by aquynh** [comment]
Done, we moved to a new home, while retaining everything.

https://github.com/capstone-engine/capstone

**Comment by aeflores** [comment]
Hi @aquynh, we at @GrammaTech have been maintaining a fork https://github.com/GrammaTech/capstone/tree/next  of capstone with some fixes. Some of these made it into the official capstone e.g. https://github.com/capstone-engine/capstone/pull/1689 https://github.com/capstone-engine/capstone/pull/1600, other are still waiting https://github.com/capstone-engine/capstone/pull/1754. We would love to continue collaborating and contributing to the project more generally.

More recently, we started looking into updating the llvm tables, since we found some errors in the current ones. We had some difficulties simply updating the tables to a newer version of llvm (vertion 13), so for now we are just fixing the identified failures in the current tables https://github.com/GrammaTech/capstone/pull/7.  Maybe with a some help, we can get to a point where we can contribute on that front too.

We are very excited to see the organization being created, and we are looking forward to collaborate!

**Comment by aquynh** [comment]
Great, can you start with some description on what you want to submit?

**Comment by aquynh** [comment]
> I'd be happy to help, in particular with "organization-level" items like the branching strategy in #1781. I maintain the [Rust language bindings](https://github.com/capstone-rust/capstone-rs).

thank you a lot, @tmfink! we are still trying to figure out how best to get valuable contributors like you involved, but unsure how yet. will let you know once we are ready

**Comment by SweetVishnya** [comment]
Is there any date planned for further rc or 5.0 releases?

**Comment by XVilka** [comment]
@SweetVishnya see the work of auto-sync regarding the release: https://github.com/capstone-engine/capstone/pull/1949

**Comment by XVilka** [comment]
@aquynh @kabeor should be this one closed now?

**Comment by kabeor** [comment]
Will close this when v5.0 releasing

**Comment by kabeor** [comment]
V5.0 has been released! Closed.
