### ISSUE TITLE
Impement r2's "asm.relsub" natively in capstone

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#550]
This is.. showing absolute addresses when relative references are found in a mnemonic.

<img width="517" alt="screen shot 2015-11-19 at 23 10 57" src="https://cloud.githubusercontent.com/assets/917142/11286101/60500502-8f13-11e5-8bbe-dd900193fda2.png">

**Comment by aquynh** [comment]
Do you mean you want to propose some changes in the current API? What is
that exactly?


On Nov 20, 2015 6:15 AM, "radare" <notifications@github.com> wrote:
>
> This is.. showing absolute addresses when relative references are found
in a mnemonic.

**Comment by radare** [comment]
not in api, just adding an option to make the disassembler show absolute addresses instead of pc-relative ones in the textual representation of the instruction. even if its not accurate with the underlaying representation. it is way easier to read by humans.

**Comment by aquynh** [comment]
Feel free to implement it and send in a PR.



On Nov 20, 2015 10:27 AM, "radare" <notifications@github.com> wrote:
>
> not in api, just adding an option to make the disassembler show absolute
addresses instead of pc-relative ones in the textual representation of the
instruction. even if its not accurate with the underlaying representation.
it is way easier to read by humans.
>
>
> > On 20 Nov 2015, at 00:28, Nguyen Anh Quynh <notifications@github.com>
wrote:
> >
> > Do you mean you want to propose some changes in the current API? What is
> > that exactly?
> >
> >
> > On Nov 20, 2015 6:15 AM, "radare" <notifications@github.com> wrote:
> > >
> > > This is.. showing absolute addresses when relative references are
found
> > in a mnemonic.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > —
> > Reply to this email directly or view it on GitHub <
https://github.com/aquynh/capstone/issues/550#issuecomment-158233039>.
