### ISSUE TITLE
REP RET doesn't have REP prefix listed

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#664]
The instruction `F3 C3` has `rep` prefix (it's used to avoid problems with branch predictors on some AMD CPUs). But although capstone does understand the instruction, it renders it just as `ret` and its list of prefixes doesn't include `rep`.

**Comment by aquynh** [comment]
i think it is right to remove REP in the output assembly. do you want to have F3 as a prefix?

**Comment by 10110111** [comment]
I just want Capstone to not remove the information. It may be OK to remove `rep` from textual representation of the instruction, but the details still must have as much of the information as possible about the actual instruction.
As I remember, one of the Capstone's goals was to be able to disassemble tricky cases. IMO, extraneous prefixes are tricky too, and the user should be able to know about them.

**Comment by EdwardLarson** [comment]
It seems right to include the `rep` prefix in the output. Otherwise information is lost. For example since Keystone understands `ret` vs `rep ret`, if you were to disassemble a `rep ret` instruction in Capstone then assemble that output with Keystone, your output would be missing the prefix and be one byte shorter.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
