### ISSUE TITLE
[x86] XMM register used in address calculation for EVEX instruction

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#905]
The EVEX instruction uses an XMM register in the address calculation, which it should not.

Bytes:          62 a1 2d d4 db 6c b6 08 
Output:         vpandd 32(%rsi,%xmm14,4){1to16}, %zmm26, %zmm21 {%k4} {z}
Error from gas: unsupported vector index register for `vpandd'
Expected:       vpandd 0x20(%rsi, %r14, 4){1to16}, %zmm26, %zmm21{%k4}{z}

**Comment by aquynh** [comment]
this is the output of the "next" branch:

```
$ cstool x64 "62 a1 2d d4 db 6c b6 08"
0  62a12dd4db6cb608 .  vpandd	zmm21 {k4} {z}, zmm26, dword ptr [rsi + xmm14*4 + 0x20]{1to16}
```

**Comment by nathanhjay** [comment]
I'm not sure I know exactly whether xmm14 is valid in the address calculation there, but I can tell you that it won't assemble with gas version 2.26 and that XED produces this output for that input:

`vpandd zmm21{k4}{z}, zmm26, dword ptr [rsi+r14*4+0x20]{1to16}`

**Comment by hlide** [comment]
If I'm not wrong _{1to16}_ is a broadcast so it would make sense for having _r14_ and not _xmm14_ because it would mean to read a _dword_ value through _r14_ as a base and broadcasting it into a vector of 16 _dwords_ to 'and' with _zmm21_ conditionally (mask _k4_). Using _xmm14_ would mean using the 4 dwords packed as bases, which is wrong because you'll need _zmm14_ instead to have 16 bases and the broadcast _{1to16}_ would not make sense as well.

However I may be wrong because I'm not totally familiar with AVX512.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
